package com.backbase.expert.extensions.sushi.processors;

import com.backbase.expert.extensions.sushi.processors.transformers.javascript.JavascriptRewriteInlineLinksProcessor;
import org.junit.Test;

/**
 * Created by bartv on 30/08/14.
 */
public class TestJavascriptRewriteInlineLinksProcessor {

    @Test
    public void testRewrite() throws Exception {

        JavascriptRewriteInlineLinksProcessor processor = new JavascriptRewriteInlineLinksProcessor();
//        ApplicationViewState applicationViewState = new ApplicationViewState();
//        applicationViewState.setId("w00t");
//        applicationViewState.setInitialRemoteUrl("http://localhost:8880/meniga/standalonetransactionswidget.jsp");
//        applicationViewState.setCurrentRemoteUrl("http://localhost:8880/meniga/standalonetransactionswidget.jsp");
//
//        SushiRecipe recipe = new SushiRecipe();
//        recipe.setRemoteHost("http://localhost:8880");
//        recipe.setRemoteHttpPath("/meniga/standalonetransactionswidget.jsp");
//        recipe.setServletPath("/services");
//        recipe.setContextPath("/portalserver");
//        applicationViewState.setSushiRecipe(recipe);
//
//
//        Exchange exchange = new DefaultExchange(new MockEndpoint());
//        exchange.setProperty(SushiConstants.SUSHI_RECIPE, recipe);
//        exchange.setProperty(SushiConstants.SUSHI_APPLICATION_VIEW_STATE,applicationViewState);
//
//        Element element = Jsoup.parse("<script type=\"text/javascript\">\n" +
//                "\t//note: _menigaInfoWidgetPreload is dummy data and needs to be generated by the webapp\n" +
//                "\tvar _menigaInfoWidgetPreload = {\"Data\":{\"Email\":\"demo@meniga.is\",\"PersonId\":\"1\",\"UserId\":\"1\",\"RealmIdentifier\":\"default\",\"UserIdentifier\":\"demo@meniga.is\",\"LastLoginDate\":\"2013-10-11 09:22\",\"AdminId\":\"\",\"Phone\":null,\"IPAddress\":\"::1\"},\"Terms\":{ \"Body\": \"\", \"AcceptDate\": null }};\n" +
//                "\n" +
//                "\tvar _menigaLoginUrl = '/meniga/Auth';\n" +
//                "\tvar _menigaBaseUrl = '/meniga';\n" +
//                "\tvar _menigaApiUrl = '/meniga';\n" +
//                "\t</script>");
//
//        exchange.getIn().setBody(element);
//

//        processor.process(exchange);


    }
}
